#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

GREEN='\033[0;32m'
LIGHT_BLUE='\033[1;34m'
NO_COLOR='\033[0m'


echo -e "${LIGHT_BLUE}!${NO_COLOR} Checking Lint"
pnpm run lint --fix || exit $
echo -e "${GREEN}✔${NO_COLOR} Done Running Lint"

echo -e "${LIGHT_BLUE}!${NO_COLOR} Prettier is Formatting Staged Files"
pnpm lint-staged

echo -e "${GREEN} Formatted"
echo -e "${GREEN}✔${NO_COLOR} Done Running Prettier"

echo -e "${LIGHT_BLUE}!${NO_COLOR} Checking for Circular Dependency"
pnpm cruise || exit $

echo -e "${GREEN}✔${NO_COLOR} Done Running Pre-commit\n"